workers = 1          # local only; production: 4 with PROMETHEUS_MULTIPROC_DIR set
worker_class = "gthread"
threads = 4
timeout = 30
graceful_timeout = 30
keepalive = 5
accesslog = "-"
errorlog = "-"
preload_app = True
bind = "0.0.0.0:8000"
