# Automatically opens PRs with the `dependencies` label to bump outdated dependencies on a schedule

# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Update python packages in the webapp
  - package-ecosystem: "pip"
    directory: "/src/dsv-app"
    target-branch: "main"
    schedule:
      interval: "weekly"

  # Update docker base image in the webapp
  - package-ecosystem: "docker"
    directory: "/src/dsv-app"
    target-branch: "main"
    schedule:
      interval: "weekly"
  # Update docker base image in the database
  - package-ecosystem: "docker"
    directory: "/src/dsv-db"
    target-branch: "main"
    schedule:
      interval: "weekly"

  # Update GitHub Actions versions in workflows files
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"