name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '⚙️ CI/CD'
    labels:
      - 'ci-cd'
  - title: '🔨 Build & Dependencies'
    labels:
      - 'build'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.      
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'fix'
template: |
  ## What's Changed

  $CHANGES

  ## Deployment Notes

  - [Install guide](docs/how-to/install-guide.md): How to provision and install DineSafeViz.
  - [Deployment guide](docs/how-to/deploy/deploy.md): How to deploy DineSafeViz on existing infrastructure.
  - [Administration guide](docs/how-to/admin-guide.md): How to configure and manage DineSafeViz.

  ## Post Implementation Verification (PIV)

  - [PIV guide](docs/how-to/operations/piv.md): How to verify DineSafeViz is working as expected after deployment.

  ## Rollback Instructions

  - Rollback guide - TBD

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
