apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: dinesafe-postgres
    type: postgres
    access: proxy
    url: ${DB_HOST}:${DB_PORT}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: ${DB_NAME}
      sslmode: disable
      postgresVersion: 1700
    isDefault: true
    editable: true
