
# Proxmox API tokens for service accounts
vault_proxmox_api_token_secret: "aaaaaaaaaaaaaaaaaaaaaaa"
vault_packer_api_token_secret: "bbbbbbbbbbbbbbbbbbbbbb"

# PostgreSQL credentials
vault_app_analytics_db_password: "cccccccccccccccc"

# Grafana credentials
vault_analytics_admin_password: "eeeeeeeeeeeeee"

# github deploy key
vault_github_deploy_keys: |
  -----BEGIN RSA PRIVATE KEY-----
  zzzzzzzzzzzzzzzzzzzzzzzzzzzzz
  -----END RSA PRIVATE KEY-----
